name: "HAVNC"
description: "VNC straight to your dashboard"
version: "0.1.0"
slug: "havnc"
init: false
full_access: false
arch:
  - aarch64
  - amd64
ports:
  6080/tcp: 6080
options:
  url: "http://homeassistant:8123"
  resolution: "1024x600"
  require_password: false
  password: null
schema:
  url: "str"
  resolution: "str"
  require_password: "bool"
  password: "password?"
